In [5]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os

In [6]:
os.chdir ('C:\\python')
data2=pd.read_csv("audi.csv")
display(data2)

model  year  price transmission  mileage fuelType  tax   mpg  engineSize
0        A1  2017  12500       Manual    15735   Petrol  150  55.4         1.4
1        A6  2016  16500    Automatic    36203   Diesel   20  64.2         2.0
2        A1  2016  11000       Manual    29946   Petrol   30  55.4         1.4
3        A4  2017  16800    Automatic    25952   Diesel  145  67.3         2.0
4        A3  2019  17300       Manual     1998   Petrol  145  49.6         1.0
...     ...   ...    ...          ...      ...      ...  ...   ...         ...
10663    A3  2020  16999       Manual     4018   Petrol  145  49.6         1.0
10664    A3  2020  16999       Manual     1978   Petrol  150  49.6         1.0
10665    A3  2020  17199       Manual      609   Petrol  150  49.6         1.0
10666    Q3  2017  19499    Automatic     8646   Petrol  150  47.9         1.4
10667    Q3  2016  15999       Manual    11855   Petrol  150  47.9         1.4

[10668 rows x 9 columns]

In [7]:
len(data2)

10668

In [8]:
display (data2.shape)

(10668, 9)

In [9]:
display (data2.dtypes )

model            object
year              int64
price             int64
transmission     object
mileage           int64
fuelType         object
tax               int64
mpg             float64
engineSize      float64
dtype: object

In [10]:
display (data2.isna().sum() )

model           0
year            0
price           0
transmission    0
mileage         0
fuelType        0
tax             0
mpg             0
engineSize      0
dtype: int64

In [11]:
data2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10668 entries, 0 to 10667
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   model         10668 non-null  object 
 1   year          10668 non-null  int64  
 2   price         10668 non-null  int64  
 3   transmission  10668 non-null  object 
 4   mileage       10668 non-null  int64  
 5   fuelType      10668 non-null  object 
 6   tax           10668 non-null  int64  
 7   mpg           10668 non-null  float64
 8   engineSize    10668 non-null  float64
dtypes: float64(2), int64(4), object(3)
memory usage: 750.2+ KB


In [12]:
data2.describe ()

year          price        mileage           tax           mpg  \
count  10668.000000   10668.000000   10668.000000  10668.000000  10668.000000   
mean    2017.100675   22896.685039   24827.244001    126.011436     50.770022   
std        2.167494   11714.841888   23505.257205     67.170294     12.949782   
min     1997.000000    1490.000000       1.000000      0.000000     18.900000   
25%     2016.000000   15130.750000    5968.750000    125.000000     40.900000   
50%     2017.000000   20200.000000   19000.000000    145.000000     49.600000   
75%     2019.000000   27990.000000   36464.500000    145.000000     58.900000   
max     2020.000000  145000.000000  323000.000000    580.000000    188.300000   

         engineSize  
count  10668.000000  
mean       1.930709  
std        0.602957  
min        0.000000  
25%        1.500000  
50%        2.000000  
75%        2.000000  
max        6.300000

In [13]:
x=data2.iloc[:,[0,1,3,4,5,6,7,8]].values
display(x)

array([[' A1', 2017, 'Manual', ..., 150, 55.4, 1.4],
       [' A6', 2016, 'Automatic', ..., 20, 64.2, 2.0],
       [' A1', 2016, 'Manual', ..., 30, 55.4, 1.4],
       ...,
       [' A3', 2020, 'Manual', ..., 150, 49.6, 1.0],
       [' Q3', 2017, 'Automatic', ..., 150, 47.9, 1.4],
       [' Q3', 2016, 'Manual', ..., 150, 47.9, 1.4]], dtype=object)

In [14]:
y=data2.iloc[:,[2]].values
display(y)

array([[12500],
       [16500],
       [11000],
       ...,
       [17199],
       [19499],
       [15999]], dtype=int64)

In [15]:
display(pd.DataFrame(x).head(5))

0     1          2      3       4    5     6    7
0   A1  2017     Manual  15735  Petrol  150  55.4  1.4
1   A6  2016  Automatic  36203  Diesel   20  64.2  2.0
2   A1  2016     Manual  29946  Petrol   30  55.4  1.4
3   A4  2017  Automatic  25952  Diesel  145  67.3  2.0
4   A3  2019     Manual   1998  Petrol  145  49.6  1.0

In [16]:
from sklearn.preprocessing import LabelEncoder
lb=LabelEncoder()
x[:,0]=lb.fit_transform(x[:,0])
x[:,-4]=lb.fit_transform(x[:,-4])
display (x)

array([[0, 2017, 'Manual', ..., 150, 55.4, 1.4],
       [5, 2016, 'Automatic', ..., 20, 64.2, 2.0],
       [0, 2016, 'Manual', ..., 30, 55.4, 1.4],
       ...,
       [2, 2020, 'Manual', ..., 150, 49.6, 1.0],
       [9, 2017, 'Automatic', ..., 150, 47.9, 1.4],
       [9, 2016, 'Manual', ..., 150, 47.9, 1.4]], dtype=object)

In [17]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct=ColumnTransformer(transformers = [('encoder',OneHotEncoder(),[2])],remainder='passthrough')
x=ct.fit_transform(x)
display (pd.DataFrame(x))

0    1    2  3     4      5  6    7     8    9
0      0.0  1.0  0.0  0  2017  15735  2  150  55.4  1.4
1      1.0  0.0  0.0  5  2016  36203  0   20  64.2  2.0
2      0.0  1.0  0.0  0  2016  29946  2   30  55.4  1.4
3      1.0  0.0  0.0  3  2017  25952  0  145  67.3  2.0
4      0.0  1.0  0.0  2  2019   1998  2  145  49.6  1.0
...    ...  ...  ... ..   ...    ... ..  ...   ...  ...
10663  0.0  1.0  0.0  2  2020   4018  2  145  49.6  1.0
10664  0.0  1.0  0.0  2  2020   1978  2  150  49.6  1.0
10665  0.0  1.0  0.0  2  2020    609  2  150  49.6  1.0
10666  1.0  0.0  0.0  9  2017   8646  2  150  47.9  1.4
10667  0.0  1.0  0.0  9  2016  11855  2  150  47.9  1.4

[10668 rows x 10 columns]

In [18]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x = sc.fit_transform(x)
display (pd.DataFrame(x))

0         1         2         3         4         5         6  \
0     -0.583268  1.200728 -0.712333 -1.123544 -0.046450 -0.386836  1.050783   
1      1.714479 -0.832828 -0.712333 -0.160831 -0.507834  0.483989 -0.954181   
2     -0.583268  1.200728 -0.712333 -1.123544 -0.507834  0.217781  1.050783   
3      1.714479 -0.832828 -0.712333 -0.545916 -0.046450  0.047853 -0.954181   
4     -0.583268  1.200728 -0.712333 -0.738459  0.876318 -0.971285  1.050783   
...         ...       ...       ...       ...       ...       ...       ...   
10663 -0.583268  1.200728 -0.712333 -0.738459  1.337702 -0.885343  1.050783   
10664 -0.583268  1.200728 -0.712333 -0.738459  1.337702 -0.972136  1.050783   
10665 -0.583268  1.200728 -0.712333 -0.738459  1.337702 -1.030381  1.050783   
10666  1.714479 -0.832828 -0.712333  0.609339 -0.046450 -0.688442  1.050783   
10667 -0.583268  1.200728 -0.712333  0.609339 -0.507834 -0.551913  1.050783   

              7         8         9  
0      0.357147  0.357550 -0.880218  
1     -1.578323  1.037130  0.114925  
2     -1.429440  0.357550 -0.880218  
3      0.282706  1.276528  0.114925  
4      0.282706 -0.090355 -1.543647  
...         ...       ...       ...  
10663  0.282706 -0.090355 -1.543647  
10664  0.357147 -0.090355 -1.543647  
10665  0.357147 -0.090355 -1.543647  
10666  0.357147 -0.221637 -0.880218  
10667  0.357147 -0.221637 -0.880218  

[10668 rows x 10 columns]

In [19]:
from sklearn.model_selection import train_test_split
(x_train,x_test,y_train,y_test) = train_test_split(x,y,test_size=0.2,random_state=0)

In [20]:
import warnings
warnings.filterwarnings('ignore')
from sklearn.ensemble import RandomForestRegressor
regression = RandomForestRegressor(random_state=0)
regression.fit(x_train,y_train)

RandomForestRegressor(random_state=0)

In [21]:
y_pred = regression.predict(x_test)
display (y_pred)

array([14337.15, 23450.35, 27330.07, ..., 46275.18, 31359.  ,  9929.62])

In [22]:
y_pred=y_pred.reshape(len(y_pred),1)
y_test=y_test.reshape(len(y_test),1)

In [23]:
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

[[14337.15 14998.  ]
 [23450.35 21950.  ]
 [27330.07 28990.  ]
 ...
 [46275.18 45995.  ]
 [31359.   30500.  ]
 [ 9929.62  8400.  ]]


In [24]:
from sklearn.metrics import r2_score,mean_absolute_error
print  ('R2 Score ', r2_score(y_test, y_pred))
print  ('Mean Absolute Error', mean_absolute_error(y_test,y_pred))

R2 Score  0.9536134841307546
Mean Absolute Error 1538.730980670462


In [25]:
from sklearn.linear_model import LinearRegression
reg = LinearRegression()
reg.fit(x_train,y_train)

LinearRegression()

In [26]:
y_pred = reg.predict(x_test)
display (y_pred)

array([[13091.52500293],
       [29387.52500293],
       [31823.52500293],
       ...,
       [42695.52500293],
       [31583.52500293],
       [ 7311.52500293]])

In [27]:
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

[[13091.52500293 14998.        ]
 [29387.52500293 21950.        ]
 [31823.52500293 28990.        ]
 ...
 [42695.52500293 45995.        ]
 [31583.52500293 30500.        ]
 [ 7311.52500293  8400.        ]]


In [28]:
from sklearn.metrics import r2_score,mean_absolute_error
print  ('R2 Score ', r2_score(y_test, y_pred))
print  ('Mean Absolute Error', mean_absolute_error(y_test,y_pred))

R2 Score  0.7915402594567064
Mean Absolute Error 3379.8051549247084


In [29]:
y_pred = reg.predict(x)
display (y_pred)

array([[14659.52500293],
       [20531.52500293],
       [13835.52500293],
       ...,
       [19443.52500293],
       [20907.52500293],
       [16735.52500293]])

In [32]:
result = pd.concat([data2,pd.DataFrame(y_pred)],axis=1)
display( result)

model  year  price transmission  mileage fuelType  tax   mpg  \
0        A1  2017  12500       Manual    15735   Petrol  150  55.4   
1        A6  2016  16500    Automatic    36203   Diesel   20  64.2   
2        A1  2016  11000       Manual    29946   Petrol   30  55.4   
3        A4  2017  16800    Automatic    25952   Diesel  145  67.3   
4        A3  2019  17300       Manual     1998   Petrol  145  49.6   
...     ...   ...    ...          ...      ...      ...  ...   ...   
10663    A3  2020  16999       Manual     4018   Petrol  145  49.6   
10664    A3  2020  16999       Manual     1978   Petrol  150  49.6   
10665    A3  2020  17199       Manual      609   Petrol  150  49.6   
10666    Q3  2017  19499    Automatic     8646   Petrol  150  47.9   
10667    Q3  2016  15999       Manual    11855   Petrol  150  47.9   

       engineSize             0  
0             1.4  14659.525003  
1             2.0  20531.525003  
2             1.4  13835.525003  
3             2.0  19807.525003  
4             1.0  17379.525003  
...           ...           ...  
10663         1.0  19219.525003  
10664         1.0  19315.525003  
10665         1.0  19443.525003  
10666         1.4  20907.525003  
10667         1.4  16735.525003  

[10668 rows x 10 columns]

In [34]:
from sklearn.model_selection import RandomizedSearchCV

n_estimators = [int(x) for x in np.linspace(start = 80, stop = 1500, num = 10)]
max_features = ['auto', 'sqrt']
max_depth = [int(x) for x in np.linspace(6, 45, num = 5)]
min_samples_split = [2, 5, 10, 15, 100]
min_samples_leaf = [1, 2, 5, 10]

# create random grid

rand_grid={'n_estimators': n_estimators,
               'max_features': max_features,
               'max_depth': max_depth,
               'min_samples_split': min_samples_split,
               'min_samples_leaf': min_samples_leaf}

rf=RandomForestRegressor()

rCV=RandomizedSearchCV(estimator=rf,param_distributions=rand_grid,scoring='neg_mean_squared_error',n_iter=3,cv=3,random_state=42, n_jobs = 1)


In [35]:
import warnings
warnings.filterwarnings('ignore')

rCV.fit(x_train,y_train)

RandomizedSearchCV(cv=3, estimator=RandomForestRegressor(), n_iter=3, n_jobs=1,
                   param_distributions={'max_depth': [6, 15, 25, 35, 45],
                                        'max_features': ['auto', 'sqrt'],
                                        'min_samples_leaf': [1, 2, 5, 10],
                                        'min_samples_split': [2, 5, 10, 15,
                                                              100],
                                        'n_estimators': [80, 237, 395, 553, 711,
                                                         868, 1026, 1184, 1342,
                                                         1500]},
                   random_state=42, scoring='neg_mean_squared_error')

In [36]:
rf_pred=rCV.predict(x_test)
display (rf_pred)

array([14025.97390543, 23776.22387456, 28573.82360212, ...,
       48358.80053072, 31318.04306144, 10044.49457506])

In [37]:
from sklearn.metrics import mean_absolute_error,mean_squared_error
print('MAE',mean_absolute_error(y_test,rf_pred))
print('MSE',mean_squared_error(y_test,rf_pred))


MAE 1505.5229308386272
MSE 5656885.922017979


In [38]:
display(r2_score(y_test,rf_pred))

0.9588338663672809